### PR TITLE
UPDATE: Change kakaomap and googlemap address of the shop

### PR DESCRIPTION
**Pull request by samwina**
## What is this PR for:
The barber shop changed the address to a new place so I simple copied the latitude of the new address from google map and kakao map and update the old address in the code.

### CODE REVIEW

**Comment by untilhamza** [comment]
@samwina  Please add a description for what your PR is doing above

**Comment by untilhamza** [comment]
Please update the version as well

**Comment by samwina** [comment]
What do you mean by updating the version ?

> Please update the version as well

**Review by untilhamza — APPROVED** [review]
LGTM, you can merge now

**Pull request merged**
